### ISSUE TITLE
what  a role does SAAT plays in model training?  

### ISSUE THREAD

**Issue by mingliutju** [zhuccly/SAAT#1]
Hi, thanks for your contribution.  SAAT maybe performed as special data augmentation likes MixUp ？Could you show some 
 perturbations?

**Comment by zhuccly** [comment]
> Hi, thanks for your contribution. SAAT maybe performed as special data augmentation likes MixUp ？Could you show some perturbations?

Thank you very much for your interest and sorry for the late reply. Our goal is to make SAAT adaptively generate hard samples for the detector beyond the handcrafted transformations. In fact, this is a form of data augmentation, but it differs from and complements existing handcrafted augmentations. Our experiments only used the common handcrafted augmentation such as random rotation, random scaling, noising, distorting color, etc. We did not use the more special data augmentation such as MixUp. Finally, we show perturbations of different strategies in the directory: SAAT/Fig/Attacks.png. And our supplementary material shows more details, URL: https://openaccess.thecvf.com/content/ICCV2021/supplemental/Zhu_Improving_Robustness_of_ICCV_2021_supplemental.pdf

**Comment by mingliutju** [comment]
It is a really fantastic work，thank you very much!
